In [1]:
import numpy as np
arr1 = [10,20,30,40,50]
arr2 = [2,4,5,8,10]
a  = np.array(arr1)
b = np.array(arr2)
print(a)
print(b)

[10 20 30 40 50]
[ 2  4  5  8 10]


In [2]:
print(a+b)

[12 24 35 48 60]


In [3]:
print(a-b)
print(a*b)
print(a/b)

[ 8 16 25 32 40]
[ 20  80 150 320 500]
[5. 5. 6. 5. 5.]


In [4]:
print(a.dot(b))

1070


In [5]:
sclr  = 5
print(a)
print(a*sclr)

[10 20 30 40 50]
[ 50 100 150 200 250]


In [6]:
def my_func(x,y):
    if(x>y):
        return x-y
    else:
        return x+y
    
arr1 = [10,4,20]
arr2 = [2,3,30]
vec_func = np.vectorize(my_func)
print(arr1)
print(arr2)
print(vec_func(arr1,arr2))

[10, 4, 20]
[2, 3, 30]
[ 8  1 50]
