In [1]:
import numpy as file
a = file.array([28, 8, 4, 7])
print(a)

[28  8  4  7]


In [2]:
import numpy as file
a = file.array([28, 8, 4, 7])
print(a)

[28  8  4  7]


In [3]:
import numpy as file
a = file.array([[28, 8, 4], [30, 3, 5], [13, 12, 4], [7, 12, 81]])
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [4]:
a = file.array([[28, 8, 4], [30, 3, 5], [13, 12, 4], [7, 12, 81]])
print(a)


[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [6]:
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [7]:
a = file.zeros((31,20,54))
print(a)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [8]:
a = file.array([[28, 8, 4], [30, 3, 5], [13, 12, 4], [7, 12, 81]])
print("The elements in  the array are", a)

The elements in  the array are [[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [9]:
b = file.full((3,3), 28)
print(b)

[[28 28 28]
 [28 28 28]
 [28 28 28]]


In [10]:
b = file.full((3,3), 28)
print(b)

[[28 28 28]
 [28 28 28]]


In [11]:
b = file.full(4, 28)
print(b)

[28 28 28 28]


In [12]:
c = file.random.random(4,3)
print(c)

TypeError: random() takes at most 1 positional argument (2 given)

In [13]:
c = file.random.random(4)
print(c)

[0.7876519  0.99069192 0.83482097 0.44817698]


In [14]:
c = file.random.random(4,3)
print(math.floor(c*6)

SyntaxError: unexpected EOF while parsing (1406717975.py, line 2)

TypeError: random() takes at most 1 positional argument (2 given)

In [18]:
c = file.random.random(4)
print(c*6)

[2.31462588 3.93364431 4.28535175 4.41171379]


In [19]:
c = file.random.random((4,3)
print(c*6)

SyntaxError: invalid syntax (1486264636.py, line 2)

In [20]:
c = file.random.random((4,3))
print(c*6)

[[0.83833179 5.92910544 1.97919003]
 [3.99854082 2.91924736 2.25951797]
 [5.96141552 5.54786509 5.16881595]
 [3.87307345 5.7203588  1.5249303 ]]


In [21]:
d = file.arange(8, 28, 4)
print(d)

[ 8 12 16 20 24]


In [22]:
a.reshape(3,3)
print(a)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [23]:
a.reshape(4,3)
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [26]:
a.reshape(3,4)
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [27]:
a.reshape(4,3)
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [28]:
e = a.reshape(4,3)
print(e)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [29]:
e = a.reshape(3,4)
print(e)

[[28  8  4 30]
 [ 3  5 13 12]
 [ 4  7 12 81]]


In [30]:
print(a.flatten())

[28  8  4 30  3  5 13 12  4  7 12 81]


In [31]:
print(e.flatten())

[28  8  4 30  3  5 13 12  4  7 12 81]


In [33]:
print(e.shape)

(3, 4)


In [34]:
print(e.ndim)

2


In [35]:
print(e.size)

12


In [36]:
print(e.dtype)

int32


In [37]:
f = a.astype('f')
print(f)

[[28.  8.  4.]
 [30.  3.  5.]
 [13. 12.  4.]
 [ 7. 12. 81.]]


In [39]:
f = a.astype('f')
print(f)

[[28.  8.  4.]
 [30.  3.  5.]
 [13. 12.  4.]
 [ 7. 12. 81.]]


In [40]:
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [41]:
print(a[0:3:2])

[[28  8  4]
 [13 12  4]]


In [42]:
print(a[0:3])

[[28  8  4]
 [30  3  5]
 [13 12  4]]


In [43]:
print(a[1::])

[[30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [44]:
print(a[1])

[30  3  5]


In [45]:
print(a[-1::])

[[ 7 12 81]]


In [46]:
print(a[-1::2])

[[ 7 12 81]]


In [47]:
print(a[-1::1])

[[ 7 12 81]]


In [48]:
print(a[1::1])

[[30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [49]:
print(a[0, 1:3])

[8 4]


In [50]:
print(a[0, 0:1])

[28]


In [51]:
print(a[1:, 1:])

[[ 3  5]
 [12  4]
 [12 81]]


In [52]:
print(a)

[[28  8  4]
 [30  3  5]
 [13 12  4]
 [ 7 12 81]]


In [53]:
print(a[:,1])

[ 8  3 12 12]


In [54]:
print(a[-1:-3:1])

[]


In [55]:
print(a[-1:-3:-1])

[[ 7 12 81]
 [13 12  4]]


In [1]:
print(a[-1:-3:-1])

NameError: name 'a' is not defined