In [1]:
import numpy as np
arr = np.array([[-1,2, 0, 4], [4, 6, 8, 10], [2, 3, 5, 7], [28, 8, 4, 7]])
temp = arr[[0,1,2,3],[3,2,1,0]]
print(temp)

[ 4  8  3 28]


In [3]:
arr = np.array([[-1,2, 0, 4], [4, 6, 8, 10], [2, 3, 5, 7], [28, 8, 4, 7]])
print(arr)


[[-1  2  0  4]
 [ 4  6  8 10]
 [ 2  3  5  7]
 [28  8  4  7]]


In [23]:
arr = np.array([[-1,2, 0, 4], [4, 6, 8, 10], [2, 3, 5, 7], [28, 8, 4, 7]])
print(arr[0:1:2])

[[-1  2  0  4]]


In [6]:
cond = arr>3
temp = arr[cond]
print(temp)

[ 4  4  6  8 10  5  7 28  8  4  7]


In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [13]:
arr1 = np.array([28,8,4])
arr2 = np.array([30,3,5])
arr = np.concatenate((arr1,arr2))
print(arr)

[28  8  4 30  3  5]


In [14]:
arr = np.hstack((arr1,arr2))
print(arr)

[28  8  4 30  3  5]


In [15]:
arr = np.vstack((arr1,arr2))
print(arr)

[[28  8  4]
 [30  3  5]]


In [16]:
arr = np.dstack((arr1,arr2))
print(arr)

[[[28 30]
  [ 8  3]
  [ 4  5]]]


In [17]:
arr = np.array([30,3,5,28,4,8])
newarr = np.array_split(arr,3)
print(newarr)

[array([30,  3]), array([ 5, 28]), array([4, 8])]


In [19]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[30  3]
[ 5 28]
[4 8]
