In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4,3])
x = np.where(arr==3)
print(x)

(array([2, 7], dtype=int64),)


In [2]:
x = np.where(arr%2==0)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [3]:
x = np.searchsorted(arr,3,side='left')
print(x)

2


In [5]:
arr = np.array([3,2,1,0])
print(np.sort(arr))

[0 1 2 3]


In [6]:
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [7]:
arr = np.array([41,42,43,44,45,59,63])
filter_arr = arr>42
newarr = arr[filter_arr]
print(filter_arr)

[False False  True  True  True  True  True]
